-- Insert new questions with randomly assigned genders
INSERT INTO questions (text, region, gender) VALUES
    ('What is your opinion on remote work?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('How do you manage stress at work?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What are your hobbies outside work?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What is your favorite project you’ve worked on?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s the best advice you’ve received in your career?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('How do you balance work and personal life?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s your approach to learning new skills?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('How do you stay motivated at work?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s the most challenging aspect of your job?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s the key to effective teamwork?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What do you think about hybrid work models?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What are the biggest trends in your industry?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('How do you handle tight deadlines?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s your approach to problem-solving?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s your strategy for career growth?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('How do you handle difficult clients or colleagues?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What role does technology play in your work?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s the most important skill for success?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('How do you measure success in your role?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s your process for setting professional goals?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s your favorite book related to your field?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('How do you stay updated on industry news?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s the biggest challenge your industry faces?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What advice would you give to someone starting in your field?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('How do you prioritize tasks during busy periods?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('How do you manage a heavy workload?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s your strategy for dealing with failure?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('How do you maintain creativity in your work?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s your approach to time management?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('How do you approach conflict resolution?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s the most rewarding part of your job?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What do you do to relax after work?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s your philosophy on work-life balance?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s your biggest career achievement so far?', 'Singapore', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),

    ('How do you manage stress during tight deadlines?', 'New York', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s your strategy for learning new technologies?', 'New York', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s the most exciting project you’ve worked on?', 'New York', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s the most valuable lesson you’ve learned in your career?', 'New York', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What’s your view on the future of the workforce?', 'New York', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END),
    ('What are the biggest trends affecting your industry?', 'New York', CASE WHEN random() > 0.5 THEN 'male' ELSE 'female' END);
