-- Insert questions for both regions
INSERT INTO questions (text, region) VALUES
    ('What is your opinion on remote work?', 'Singapore'),
    ('How do you manage stress at work?', 'Singapore'),
    ('What are your hobbies outside work?', 'Singapore'),
    ('What is your favorite project you’ve worked on?', 'Singapore'),
    ('What’s the best advice you’ve received in your career?', 'Singapore'),
    ('How do you balance work and personal life?', 'Singapore'),
    ('What’s your approach to learning new skills?', 'Singapore'),
    ('How do you stay motivated at work?', 'Singapore'),
    ('What’s the most challenging aspect of your job?', 'Singapore'),
    ('What’s the key to effective teamwork?', 'Singapore'),
    ('What do you think about hybrid work models?', 'Singapore'),
    ('What are the biggest trends in your industry?', 'Singapore'),
    ('How do you handle tight deadlines?', 'Singapore'),
    ('What’s your approach to problem-solving?', 'Singapore'),
    ('What’s your strategy for career growth?', 'Singapore'),
    ('How do you handle difficult clients or colleagues?', 'Singapore'),
    ('What role does technology play in your work?', 'Singapore'),
    ('What’s the most important skill for success?', 'Singapore'),
    ('How do you measure success in your role?', 'Singapore'),
    ('What’s your process for setting professional goals?', 'Singapore'),
    ('What’s your favorite book related to your field?', 'Singapore'),
    ('How do you stay updated on industry news?', 'Singapore'),
    ('What’s the biggest challenge your industry faces?', 'Singapore'),
    ('What advice would you give to someone starting in your field?', 'Singapore'),
    ('How do you prioritize tasks during busy periods?', 'Singapore'),
    ('How do you manage a heavy workload?', 'Singapore'),
    ('What’s your strategy for dealing with failure?', 'Singapore'),
    ('How do you maintain creativity in your work?', 'Singapore'),
    ('What’s your approach to time management?', 'Singapore'),
    ('How do you approach conflict resolution?', 'Singapore'),
    ('What’s the most rewarding part of your job?', 'Singapore'),
    ('What do you do to relax after work?', 'Singapore'),
    ('What’s your philosophy on work-life balance?', 'Singapore'),
    ('What’s your biggest career achievement so far?', 'Singapore'),
    ('What skills are you currently working on improving?', 'Singapore'),
    ('What’s your opinion on mentorship in the workplace?', 'Singapore'),
    ('How do you stay productive when working remotely?', 'Singapore'),
    ('What’s your biggest professional goal for the next year?', 'Singapore'),
    ('How do you keep track of your professional growth?', 'Singapore'),
    ('What motivates you to perform your best?', 'Singapore'),
    ('What’s the best decision you’ve made in your career?', 'Singapore'),
    ('How do you handle unexpected challenges at work?', 'Singapore'),
    ('What’s your opinion on the future of work?', 'Singapore'),
    ('How do you approach long-term career planning?', 'Singapore'),
    ('What’s the most innovative thing you’ve worked on?', 'Singapore'),
    ('How do you handle feedback from colleagues or supervisors?', 'Singapore'),
    ('What role do you think AI will play in your industry?', 'Singapore'),
    ('What’s your advice for maintaining a positive attitude at work?', 'Singapore'),
    ('How do you manage change in the workplace?', 'Singapore'),
    ('What’s your opinion on the importance of company culture?', 'Singapore');

-- Repeat similarly for New York
INSERT INTO questions (text, region) VALUES
    ('How do you balance your personal and work life?', 'New York'),
    ('How do you deal with stress during tight deadlines?', 'New York'),
    ('What’s your strategy for learning new technologies?', 'New York'),
    ('What’s the most exciting project you’ve worked on?', 'New York'),
    ('What’s the most valuable lesson you’ve learned in your career?', 'New York'),
    ('How do you manage your time efficiently?', 'New York'),
    ('What’s your approach to professional development?', 'New York'),
    ('What are your thoughts on remote work?', 'New York'),
    ('How do you stay motivated while working from home?', 'New York'),
    ('What’s your opinion on flexible working hours?', 'New York'),
    ('What’s the best career advice you’ve received?', 'New York'),
    ('How do you stay updated on industry trends?', 'New York'),
    ('What’s the most challenging aspect of working remotely?', 'New York'),
    ('How do you stay productive during long workdays?', 'New York'),
    ('What’s your approach to achieving work-life balance?', 'New York'),
    ('How do you handle feedback from supervisors?', 'New York'),
    ('What’s your advice for someone starting in your field?', 'New York'),
    ('How do you approach teamwork in a virtual environment?', 'New York'),
    ('What’s your strategy for career growth?', 'New York'),
    ('What’s your favorite professional book or podcast?', 'New York'),
    ('How do you measure success in your role?', 'New York'),
    ('What’s your opinion on hybrid work models?', 'New York'),
    ('What’s your process for setting career goals?', 'New York'),
    ('How do you handle challenging clients or colleagues?', 'New York'),
    ('What role does technology play in your daily work?', 'New York'),
    ('What’s the most important skill for career success?', 'New York'),
    ('What’s your biggest professional challenge?', 'New York'),
    ('What’s your philosophy on innovation in the workplace?', 'New York'),
    ('How do you approach time management?', 'New York'),
    ('What’s your strategy for conflict resolution?', 'New York'),
    ('What’s your biggest career achievement?', 'New York'),
    ('What’s your process for managing multiple projects?', 'New York'),
    ('What’s your opinion on mentorship?', 'New York'),
    ('How do you stay productive during long workweeks?', 'New York'),
    ('What’s your biggest professional goal for the upcoming year?', 'New York'),
    ('How do you track your professional growth?', 'New York'),
    ('What motivates you to succeed at work?', 'New York'),
    ('What’s the best professional decision you’ve made?', 'New York'),
    ('How do you handle unexpected challenges at work?', 'New York'),
    ('What’s your view on the future of the workforce?', 'New York'),
    ('What’s the most innovative project you’ve worked on?', 'New York'),
    ('How do you approach feedback from coworkers?', 'New York'),
    ('What role will AI play in the future of work?', 'New York'),
    ('What’s your advice for maintaining a positive mindset at work?', 'New York'),
    ('How do you manage change in your industry?', 'New York'),
    ('What’s your view on the importance of workplace culture?', 'New York'),
    ('What are the biggest trends affecting your industry?', 'New York'),
    ('How do you stay balanced during a busy work season?', 'New York');
